steps:
  # Build base image menggunakan Docker builder resmi Google
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'asia-southeast2-docker.pkg.dev/project-abe744c2-29af-4c9b-ab9/erp-pesantren-repo/php8.3-pesantren-base:latest', 
      '-f', 'Dockerfile.base', 
      '.'
    ]

# Ganti 'erp-pesantren-repo' dengan nama repositori Anda di Artifact Registry
images:
  - 'asia-southeast2-docker.pkg.dev/project-abe744c2-29af-4c9b-ab9/erp-pesantren-repo/php8.3-pesantren-base:latest'
