FROM php:8.3-apache

# 1. Install system dependencies, PHP extensions, AND Node.js
# Memasukkan Nodejs ke base image menghemat 40-60 detik setiap build aplikasi.
RUN apt-get update && apt-get install -y \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    git \
    curl \
    libicu-dev \
    libzip-dev \
    && docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd intl zip \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 2. Install Composer (Global)
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# 3. Enable Apache Modules
RUN a2enmod rewrite

# 4. Set working directory
WORKDIR /var/www/html
